### ISSUE TITLE
Installation issues at the `make` step

### ISSUE THREAD

**Issue by lauren-mak** [anuradhawick/seq2vec#3]
I'm trying to install `seq2vec` as part of the OLBR workflow but I've run into some errors at the `make` step that look like the following:

```
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/mutex:36,
                 from /home/lam4003/bin/seq2vec/main.cpp:3:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/c++0x_warning.h:31:2: error: #error This file requires compiler and library support for th
e upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
In file included from /home/lam4003/bin/seq2vec/main.cpp:19:
/home/lam4003/bin/seq2vec/./include/seq.h:27: error: ISO C++ forbids initialization of member ‘seq_count’
```

One issue could be that I don't have the correct version of Boost, though the one that `cmake` is finding is close to 1.72.0:

```
cmake .. -DBoost_DEBUG=ON
-- Found Boost 1.70.0 at /home/lam4003/bin/anaconda3/lib/cmake/Boost-1.70.0
```

However, `echo $BOOST_VERSION` had no output. Is this what's causing the problems? I'm currently trying to install `libboost` via conda since I don't have sudo permissions, but `conda install -c anaconda libboost` is having issues resolving conflicts.

**Comment by anuradhawick** [comment]
Hi @lauren-mak,

Thanks for trying out OBLR. Conda version of boost is old and I always failed to get it right. Boost 1.70 is not suitable.

Could you please try the steps I have used in Google Colab version of OBLR .

Colab Link: [https://colab.research.google.com/drive/1LXQTiCatq55zIvKjguEgLiWH4bWAdyi6?usp=sharing#scrollTo=M7E9oBsYVum7](https://colab.research.google.com/drive/1LXQTiCatq55zIvKjguEgLiWH4bWAdyi6?usp=sharing#scrollTo=M7E9oBsYVum7)

I am pasting that code here;

```bash
# download boost
wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz
tar -xf boost_1_77_0.tar.gz

# install boost
cd boost_1_77_0

./bootstrap.sh --with-libraries=program_options,iostreams
./b2 install
```

This works in Google Colab which has a very old version of Boost. This should likely fix the issue by installing the latest version of boost needed. 

If root persmission causes issues, instructions to install in a different directory are available here: [https://www.boost.org/doc/libs/1_77_0/more/getting_started/unix-variants.html#id26](https://www.boost.org/doc/libs/1_77_0/more/getting_started/unix-variants.html#id26)

Let me know how it goes.

Best regards,
Anuradha

**Comment by lauren-mak** [comment]
It sadly has not! I ran into another error that was previously documented in https://github.com/boostorg/build/issues/614. I tried all of u/bergen's fixes and still failed. The errors looked like: 
```
In file included from constants.h:15,
                 from debug.h:12,
                 from mem.h:48,
                 from jam.h:526,
                 from builtins.cpp:7:
object.h:72: error: ‘nullptr’ was not declared in this scope
object.h:72: error: ISO C++ forbids initialization of member ‘obj’
object.h:72: error: making ‘obj’ static
```
So unfortunately, my system is still Boost-less. Do you have any alternate ways to install Boost?

**Comment by anuradhawick** [comment]
What is your operating system, version, etc?

I can try to compile this on my machine and put the binary here. Not sure if it would fix the issue.

The other aliter is to run this on Colab and Download the resulting file.

**Comment by lauren-mak** [comment]
Thanks for your help! I'm on a Red Hat (release 6.3) compute cluster running Intel(R) Xeon(R) CPU E7-4870s. I would try the Colab notebook but my FastQs are huge and I can only use them on the cluster.

**Comment by lauren-mak** [comment]
Any progress on a ready-to-use binary? I tried a few other things on my end to get the proper version of Boost installed, but none of them have worked.

**Comment by anuradhawick** [comment]
Hi, I am unable to provide a binary for redhat. If I make a docker image would it work for you? Usually super computer facilities have docker support. 

Please allow me sometime to prepare the image and publish it. Thanks for your understanding.

**Comment by anuradhawick** [comment]
@lauren-mak I have updated the code to enable non-sudo compilation. This will now download the proper boost version and compile with that. No special permissions are needed.
