### ISSUE TITLE
Order of Kmers in Output 

### ISSUE THREAD

**Issue by Clarkvale** [anuradhawick/seq2vec#4]
Hi anurdhawick,

Thanks for the tool. I just had a question about the output. I understand we get a 4^N matrix of basepair combinations to represent the frequency, but are we to assume the order of kmers?  It would be helpful to have them in the header.

Thanks

**Comment by anuradhawick** [comment]
Hi,

It's not 4^N. Reverse complements are merged to the one k-mer.

I will update the code to facilitate a header.

**Comment by anuradhawick** [comment]
@Clarkvale I have created a newer tool that facilitate this functionality https://github.com/anuradhawick/kmertools

There you can get a header for counts using following command

`kmertools comp oligo -i infile.fasta -o kmer.count -H`

`-H` add header saying which k-mer corresponds to which column in output
