### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by Wytamma** [anuradhawick/seq2vec#5]
Hi @anuradhawick,

Thanks for this tool! Is there a Conda package available for seq2vec?

-W

**Comment by anuradhawick** [comment]
Hello. Not yet. I'm creating a rust version of this and plan to rollout a pip install soon. 

Thanks

**Comment by anuradhawick** [comment]
@Wytamma I have created a new tool here https://github.com/anuradhawick/kmertools

You can install it using 

```
module load rust/1.76.0 # or newer
cargo build --release
```

I am planning to great a conda distribution soon though.

**Comment by Wytamma** [comment]
Amazing! Thank you @anuradhawick
